// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWdSD2hPCmwsaKwdQ3bvlAIXiX9thOdA',
    appId: '1:767350078472:web:4f4476b8ce607a656725bd',
    messagingSenderId: '767350078472',
    projectId: 'kuri-app-7a8db',
    authDomain: 'kuri-app-7a8db.firebaseapp.com',
    storageBucket: 'kuri-app-7a8db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlH2CvxQ6IOGhpNSx2ITyUM9Ot0wSkjEs',
    appId: '1:767350078472:android:7605167c8212f67b6725bd',
    messagingSenderId: '767350078472',
    projectId: 'kuri-app-7a8db',
    storageBucket: 'kuri-app-7a8db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUHPURAtazUvcQkCk9xEcVwFjOzp6WaM',
    appId: '1:767350078472:ios:4a9de4a8d77a102d6725bd',
    messagingSenderId: '767350078472',
    projectId: 'kuri-app-7a8db',
    storageBucket: 'kuri-app-7a8db.firebasestorage.app',
    iosClientId: '767350078472-dc2ckl9gkbvk7ad09pjlmtp1235er5t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoUHPURAtazUvcQkCk9xEcVwFjOzp6WaM',
    appId: '1:767350078472:ios:4a9de4a8d77a102d6725bd',
    messagingSenderId: '767350078472',
    projectId: 'kuri-app-7a8db',
    storageBucket: 'kuri-app-7a8db.firebasestorage.app',
    iosClientId: '767350078472-dc2ckl9gkbvk7ad09pjlmtp1235er5t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoWdSD2hPCmwsaKwdQ3bvlAIXiX9thOdA',
    appId: '1:767350078472:web:7a3d1964edcef4a36725bd',
    messagingSenderId: '767350078472',
    projectId: 'kuri-app-7a8db',
    authDomain: 'kuri-app-7a8db.firebaseapp.com',
    storageBucket: 'kuri-app-7a8db.firebasestorage.app',
  );

}